import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_JP } from "next/font/google";

const font = Noto_Sans_JP({ subsets: [] });

export const metadata: Metadata = {
  title: "Band Calendar",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon-96x96.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={font.className}>{children}</body>
    </html>
  );
}
